version: "2"

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - durationcheck
    - errcheck
    - errchkjson
    - errorlint
    - errname
    - exhaustive
    - gochecknoglobals
    - gochecknoinits
    - gosec
    - govet
    - importas
    - ineffassign
    - makezero
    - maintidx
    - goconst
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unused

linters.settings:
  errcheck:
    exclude-functions:
      - (*github.com/kwo/jsonrpc2.Request).Reply
  maintidx:
    under: 30
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true

formatters:
  enable:
    - gci
    - gofumpt
  formatters.settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/kwo/jsonrpc2)

issues:
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gochecknoglobals
    - text: "shadow: declaration of \"(err|ok)\""
      linters:
        - govet
    - path: fake/fake.go
      linters:
        - errcheck
